name: storelist
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  get_it: ^8.0.2
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  fpdart: ^1.2.0
  shared_preferences: ^2.1.1  
  go_router: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
